### ISSUE TITLE
[Suggestion] Player model selector

### ISSUE THREAD

**Issue by wrefgtzweve** [Meiryi/Zombie-Shelter-PVE-Survival-Gamemode#4]
Currently theres no way for players to select a model, players can also bring in zombie player models from sandbox which is kinda cursed. Having a dedicated model system could be cool. Could maybe even have a player model shop which could be used with coins gotten from winning rounds? just a thought.

**Comment by Meiryi** [comment]
There's really no point to make a pm shop in this gamemode, also Outfitter and Enhanced PlayerModel Selector is there, use them instead
